const types = {
  GET_DEVICE: "GET_DEVICE",
  SET_LOADING: "SET_LOADING",
  SET_SPLASH_LOADING: "SET_SPLASH_LOADING",
  ERROR: "ERROR",
  SET_IS_USER_LOGGED_IN: "SET_IS_USER_LOGGED_IN",
  CHANGE_THEME: "CHANGE_THEME",
  SET_SCROLL: "SET_SCROLL",
  SET_TOKEN: "SET_TOKEN",
  SET_BLOGS: "SET_BLOGS",
  SET_BLOG: "SET_BLOG",
  SET_USER: "SET_USER",
  SET_USER_BLOGS: "SET_USER_BLOGS",
  SET_CATEGORIES: "SET_CATEGORIES",
  EDIT_BLOG: "EDIT_BLOG",
};

export default types;
